apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: hello-world2-pdb
spec:
  minAvailable: 2 # Ensure at least 2 pods are available at any time
  selector:
    matchLabels:
      app: hello-world2
